---
# Prepair hosts

- name: Install common components
  hosts: all
  roles:
  - common

- name: Prepare and install MinIO servers
  hosts: minio
  roles:
  - minio

- name: Prepare and install Docker servers
  hosts: docker
  roles:
  - docker