---
# Install and configure MinIO

- name: Ensure group "minio" exists
  ansible.builtin.group:
    name: minio
    state: present

- name: Add user minio
  user:
    name: minio
    comment: user for minio service
    group: minio
    shell: /bin/nologin
    home: /opt/minio
  become: true

- name: Append rules in firewalld for MinIO
  firewalld:
    port: 9000/tcp
    permanent: yes
    state: enabled

- name: Create a MinIO Data directory if it does not exist
  ansible.builtin.file:
    path: /data
    owner: minio
    group: minio
    state: directory

- name: Create a MinIO directory if it does not exist
  ansible.builtin.file:
    path: /opt/minio/bin
    owner: minio
    group: minio
    state: directory

- name: Download MinIO
  get_url:
    url: https://dl.minio.io/server/minio/release/linux-amd64/minio
    dest: /opt/minio/bin/minio

- name: Set owner and attributes for MinIO file
  ansible.builtin.file:
    path: /opt/minio/bin/minio
    owner: minio
    group: minio
    mode: '1754'

- name: Configure MinIO service
  template: src=minio.service.j2 dest=/etc/systemd/system/minio.service

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Configure MinIO
  template: src=minio.conf.j2 dest=/opt/minio/minio.conf

- name: Enable and start MinIO service
  ansible.builtin.service:
    name: minio
    enabled: yes
    state: started
